### PR TITLE
Add update fantasy team

### LINKED ISSUE #28: Add Update route when creating a fantasy team.
- Am not entirely sure how to best implement it, but we need a route that handles updating the fantasy team.

### LINKED ISSUE #32: Modify Create Fantasy Team Endpoint
- At the moment, when you just put in only a name to the endpoint - its shows a successful add but its not stored in the DB
`POST : http://localhost:5000/api/v1/fantasy_teams`
- Also one user can create  more than one fantasy team - which shouldn't be the case.
- A user should also have the ability to update their fantasy team name.

### PR DESCRIPTION
**Pull request by arthuroe**
- Enable update/change player from fantasy team.
- Enable delete player from fantasy team.
fixes #28 
fixes #32

### CODE REVIEW

**Comment by arthuroe** [comment]
@kisakyegordon Test if this PR handles all the issues referenced.

**Comment by kisakyegordon** [comment]
Yoo this is looking real good.

*Issues* 
- A user can edit another users team-name and they are not even admin.
- Another user can add players to another users fantasy-team
- You can update another users fantasy-team-players.

- `Critical: ` whenever a` fantasy-team-player` update happens the ` fantasy-team-player's` id in the table changes  - that change might affect us on the front-end incase ordering is being based on id-ordering.

- I also tested the Captain & Vice Captain routes - they don't seem to add or view a team captain / vice.

**Comment by kisakyegordon** [comment]
Currently the Captain / Vice Captain Option works well - but you can add a player as your captain even though they are not in your team currently.

I think it should restrict to only your current players - watchu think

**Comment by arthuroe** [comment]
@kisakyegordon fixed captain issue.

**Review by kisakyegordon — APPROVED** [review]

**Pull request merged**
